name: 'Exchange Web App Deploy (testnet)'
on:
  push:
    branches:
      - 'main'
    paths:
      - 'exchange/**'
  
  workflow_dispatch:

env:
  DOMAIN: 'goerli.proxyex.xyz'

jobs:
  build:
    name: 'Build'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Build'
        run: |
          cd exchange
          npm ci && npm run build

      - name: 'Upload'
        id: upload
        uses: aquiladev/ipfs-action@master
        with: 
          path: ./exchange/build
          pinName: ${{ env.DOMAIN }}
          service: pinata
          pinataKey: ${{ secrets.PINATA_API_KEY }}
          pinataSecret: ${{ secrets.PINATA_API_SECRET }}

      - name: 'Update dnslink'
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        run: |
          sh ./scripts/update-cf-dnslink.sh ${{ env.DOMAIN }} /ipfs/${{ steps.upload.outputs.hash }}
